# Generated by Django 4.2.6 on 2023-12-08 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 12, 9, 1, 31, 55, 216591), verbose_name='Опубликована'),
        ),
    ]
